version: "3.8"
services:
  backend:
    build: /LOCAL_DEV_ENV/back-end
    ports:
      - 5001:5001
    env_file: 
      - /LOCAL_DEV_ENV/back-end/.env
  frontend:
    build: /LOCAL_DEV_ENV/front-end
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    depends_on:
      - backend