version: "3.8"
services:
  backend:
    build: /AWS/aws-ec2
    ports:
      - 5000:5000
    env_file: 
      - /AWS/aws-ec2/.env
  frontend:
    build: /AWS/aws-amplify
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    depends_on:
      - backend